name: testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test code
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Run tests and collect coverage
        run: go test -race ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
          verbose: true
